Import library

In [22]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [23]:
dataset = pd.read_excel('dataset_skincare.xlsx')

dataset.head()

,kategori,brand,harga,promo,stok
0,Serum,Wardah,85000.0,Ya,120.0
1,Toner,Somethinc,65000.0,Tidak,80.0
2,Sunscreen,Azarine,55000.0,Ya,150.0
3,Moisturizer,Emina,75000.0,Tidak,95.0
4,Serum,NaN,92000.0,Ya,110.0


cek data missing value

In [24]:
print(dataset)

print("\nJumlah Missing Value:")
print(dataset.isnull().sum())

       kategori      brand     harga  promo   stok
0         Serum     Wardah   85000.0     Ya  120.0
1         Toner  Somethinc   65000.0  Tidak   80.0
2     Sunscreen    Azarine   55000.0     Ya  150.0
3   Moisturizer      Emina   75000.0  Tidak   95.0
4         Serum        NaN   92000.0     Ya  110.0
5     Treatment  Skintific       NaN     Ya   70.0
6         Toner     Wardah   45000.0  Tidak  130.0
7     Sunscreen  Somethinc   72000.0     Ya   85.0
8   Moisturizer      Emina   80000.0  Tidak    NaN
9         Serum    Azarine   98000.0     Ya   60.0
10    Treatment  Skintific  115000.0  Tidak   45.0
11        Toner     Wardah   50000.0     Ya  140.0
12    Sunscreen    Azarine   68000.0     Ya  100.0
13  Moisturizer  Somethinc   89000.0  Tidak   75.0
14        Serum      Emina   78000.0     Ya  125.0

Jumlah Missing Value:
kategori    0
brand       1
harga       1
promo       0
stok        1
dtype: int64


pisahkan x dan y

In [25]:
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

print(X)
print(y)

[['Serum' 'Wardah' 85000.0 'Ya']
 ['Toner' 'Somethinc' 65000.0 'Tidak']
 ['Sunscreen' 'Azarine' 55000.0 'Ya']
 ['Moisturizer' 'Emina' 75000.0 'Tidak']
 ['Serum' nan 92000.0 'Ya']
 ['Treatment' 'Skintific' nan 'Ya']
 ['Toner' 'Wardah' 45000.0 'Tidak']
 ['Sunscreen' 'Somethinc' 72000.0 'Ya']
 ['Moisturizer' 'Emina' 80000.0 'Tidak']
 ['Serum' 'Azarine' 98000.0 'Ya']
 ['Treatment' 'Skintific' 115000.0 'Tidak']
 ['Toner' 'Wardah' 50000.0 'Ya']
 ['Sunscreen' 'Azarine' 68000.0 'Ya']
 ['Moisturizer' 'Somethinc' 89000.0 'Tidak']
 ['Serum' 'Emina' 78000.0 'Ya']]
[120.  80. 150.  95. 110.  70. 130.  85.  nan  60.  45. 140. 100.  75.
 125.]


imputasi missing value

In [26]:
from sklearn.impute import SimpleImputer

# Brand
imputer_brand = SimpleImputer(strategy='most_frequent')
X[:,1:2] = imputer_brand.fit_transform(X[:,1:2])

# Harga
imputer_harga = SimpleImputer(strategy='mean')
X[:,2:3] = imputer_harga.fit_transform(X[:,2:3])

# Stok
y = y.reshape(-1,1)

imputer_stok = SimpleImputer(strategy='mean')
y = imputer_stok.fit_transform(y)

y = y.ravel()

print(X)
print(y)

[['Serum' 'Wardah' 85000.0 'Ya']
 ['Toner' 'Somethinc' 65000.0 'Tidak']
 ['Sunscreen' 'Azarine' 55000.0 'Ya']
 ['Moisturizer' 'Emina' 75000.0 'Tidak']
 ['Serum' 'Azarine' 92000.0 'Ya']
 ['Treatment' 'Skintific' 76214.28571428571 'Ya']
 ['Toner' 'Wardah' 45000.0 'Tidak']
 ['Sunscreen' 'Somethinc' 72000.0 'Ya']
 ['Moisturizer' 'Emina' 80000.0 'Tidak']
 ['Serum' 'Azarine' 98000.0 'Ya']
 ['Treatment' 'Skintific' 115000.0 'Tidak']
 ['Toner' 'Wardah' 50000.0 'Ya']
 ['Sunscreen' 'Azarine' 68000.0 'Ya']
 ['Moisturizer' 'Somethinc' 89000.0 'Tidak']
 ['Serum' 'Emina' 78000.0 'Ya']]
[120.          80.         150.          95.         110.
  70.         130.          85.          98.92857143  60.
  45.         140.         100.          75.         125.        ]


encoding

In [27]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

ct = ColumnTransformer(
    transformers=[
        ('encoder', OneHotEncoder(), [0,1,3])
    ],
    remainder='passthrough'
)

X = np.array(ct.fit_transform(X))

print(X)

[[0.0 1.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 1.0 85000.0]
 [0.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 1.0 0.0 1.0 0.0 65000.0]
 [0.0 0.0 1.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0 1.0 55000.0]
 [1.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 1.0 0.0 75000.0]
 [0.0 1.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0 1.0 92000.0]
 [0.0 0.0 0.0 0.0 1.0 0.0 0.0 1.0 0.0 0.0 0.0 1.0 76214.28571428571]
 [0.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0 1.0 1.0 0.0 45000.0]
 [0.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 1.0 72000.0]
 [1.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 1.0 0.0 80000.0]
 [0.0 1.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0 1.0 98000.0]
 [0.0 0.0 0.0 0.0 1.0 0.0 0.0 1.0 0.0 0.0 1.0 0.0 115000.0]
 [0.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 1.0 50000.0]
 [0.0 0.0 1.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0 1.0 68000.0]
 [1.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 1.0 0.0 89000.0]
 [0.0 1.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 1.0 78000.0]]


split data

In [28]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=1
)

print(X_train)
print(X_test)

[[0.0 0.0 1.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0 1.0 55000.0]
 [0.0 0.0 0.0 0.0 1.0 0.0 0.0 1.0 0.0 0.0 1.0 0.0 115000.0]
 [0.0 1.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0 1.0 92000.0]
 [0.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 1.0 0.0 1.0 0.0 65000.0]
 [1.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 1.0 0.0 89000.0]
 [0.0 1.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 1.0 85000.0]
 [0.0 1.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 1.0 78000.0]
 [0.0 1.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0 1.0 98000.0]
 [1.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 1.0 0.0 80000.0]
 [0.0 0.0 1.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0 1.0 68000.0]
 [0.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 1.0 50000.0]
 [0.0 0.0 0.0 0.0 1.0 0.0 0.0 1.0 0.0 0.0 0.0 1.0 76214.28571428571]]
[[1.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 1.0 0.0 75000.0]
 [0.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 1.0 72000.0]
 [0.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0 1.0 1.0 0.0 45000.0]]


feature scaling

In [29]:
from sklearn.preprocessing import StandardScaler

sc = StandardScaler()

X_train[:, -1:] = sc.fit_transform(X_train[:, -1:])
X_test[:, -1:] = sc.transform(X_test[:, -1:])

print(X_train)
print(X_test)

[[0.0 0.0 1.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0 1.0 -1.381127753600625]
 [0.0 0.0 0.0 0.0 1.0 0.0 0.0 1.0 0.0 0.0 1.0 0.0 2.033581041173547]
 [0.0 1.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0 1.0 0.7246093365101144]
 [0.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 1.0 0.0 1.0 0.0 -0.812009621138263]
 [1.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 1.0 0.0 0.5538738967714057]
 [0.0 1.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 1.0 0.326226643786461]
 [0.0 1.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 1.0 -0.07215604893719245]
 [0.0 1.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0 1.0 1.0660802159875316]
 [1.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 1.0 0.0 0.04166757755527996]
 [0.0 0.0 1.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0 1.0 -0.6412741813995545]
 [0.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 1.0 -1.665686819831806]
 [0.0 0.0 0.0 0.0 1.0 0.0 0.0 1.0 0.0 0.0 0.0 1.0 -0.17378428687690017]]
[[1.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 1.0 0.0 -0.24289148867590105]
 [0.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 1.0 -0.41362692841460963]
 [0.0 0.0 0